"""
Async SMTP email delivery service.

Uses aiosmtplib with the user's own SMTP server — no hosted infrastructure.
TLS mode is auto-detected from the port when smtp_use_tls=True:
  - Port 465 → implicit TLS (connection starts encrypted)
  - Port 587 / other → STARTTLS (plain connection upgraded to TLS)
Credentials are decrypted in memory and never re-stored or logged.

Public API:
    build_report_email_html(budget_name, snapshot) -> str
    send_report_email(settings, master_key, subject, html_body, pdf_attachment) -> None
    test_smtp_connection(settings, master_key) -> None
"""

import html as _html
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib
import bleach
import markdown

from app.models.report import ReportSnapshot
from app.models.settings import AppSettings
from app.services.encryption import decrypt

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_ALLOWED_EMAIL_TAGS = [
    "p", "br", "strong", "em", "b", "i", "ul", "ol", "li",
    "blockquote", "h1", "h2", "h3", "h4",
]

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_commentary(raw_markdown: str) -> str:
    """Convert AI-generated markdown to sanitised HTML safe for email."""
    html = markdown.markdown(raw_markdown, extensions=["nl2br"])
    return bleach.clean(html, tags=_ALLOWED_EMAIL_TAGS, attributes={}, strip=True)


def _check_smtp_config(settings: AppSettings) -> None:
    """
    Raise RuntimeError if SMTP fields required for delivery are missing.
    Does NOT check email_enabled — callers enforce that separately.
    """
    missing = []
    if not settings.smtp_host:
        missing.append("SMTP host")
    if not settings.smtp_port:
        missing.append("SMTP port")
    if not settings.smtp_from_email:
        missing.append("From email")
    if not settings.report_to_email:
        missing.append("To email")
    if missing:
        raise RuntimeError(f"SMTP configuration is incomplete: {', '.join(missing)}.")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_report_email_html(budget_name: str, snapshot: ReportSnapshot) -> str:
    """
    Build a simple email-safe HTML body for a report.

    HTML-escapes all dynamic values before injection. AI commentary is
    sanitised via bleach before insertion.

    Returns:
        UTF-8 HTML string suitable as the body of a MIME email.
    """
    safe_budget_name = _html.escape(budget_name)
    safe_month = _html.escape(snapshot.month)
    safe_date = _html.escape(snapshot.generated_at[:10])

    commentary_html = (
        _render_commentary(snapshot.ai_commentary)
        if snapshot.ai_commentary
        else "<p>No AI commentary was generated for this report.</p>"
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>YNAB Financial Report &mdash; {safe_month}</title>
</head>
<body style="font-family: Arial, sans-serif; max-width: 680px; margin: 0 auto; color: #222; padding: 24px;">
  <h1 style="font-size: 1.25rem; border-bottom: 2px solid #6c8fff; padding-bottom: 0.5rem; color: #1a1a2e; margin-top: 0;">
    {safe_budget_name} &mdash; {safe_month}
  </h1>
  <p style="font-size: 0.85rem; color: #888; margin-top: 0.25rem;">
    Generated {safe_date}
  </p>

  <h2 style="font-size: 0.9rem; font-weight: 700; letter-spacing: 0.05em; text-transform: uppercase; color: #6c8fff; margin-top: 1.75rem;">
    AI Analysis
  </h2>
  <div style="line-height: 1.75; font-size: 0.95rem;">
    {commentary_html}
  </div>

  <hr style="border: none; border-top: 1px solid #eee; margin: 2rem 0 1rem;">
  <p style="font-size: 0.8rem; color: #aaa; margin: 0;">
    The full report is attached as a PDF.
    Generated by <a href="https://github.com/AspiringKnowItAll/YNAB-Financial-Report" style="color: #6c8fff;">YNAB Financial Report</a>.
  </p>
</body>
</html>"""


async def send_report_email(
    settings: AppSettings,
    master_key: bytes,
    subject: str,
    html_body: str,
    pdf_attachment: bytes | None = None,
) -> None:
    """
    Deliver a report email via the user-configured SMTP server.

    Args:
        settings: AppSettings singleton (id=1). Must have email_enabled=True
                  and valid SMTP fields.
        master_key: From app.state.master_key — used to decrypt smtp_password_enc.
        subject: Email subject line.
        html_body: Rendered HTML email body (use build_report_email_html()).
        pdf_attachment: Optional PDF bytes. When provided, attached as report.pdf.

    Raises:
        RuntimeError: If email_enabled is False or SMTP config is incomplete.
        aiosmtplib.SMTPException: On SMTP connection or delivery failure.
    """
    if not settings.email_enabled:
        raise RuntimeError("Email delivery is not enabled in Settings.")
    _check_smtp_config(settings)

    smtp_password: str | None = None
    if settings.smtp_password_enc:
        smtp_password = decrypt(settings.smtp_password_enc, master_key)

    # Build MIME message
    if pdf_attachment:
        msg: MIMEMultipart = MIMEMultipart("mixed")
        msg.attach(MIMEText(html_body, "html", "utf-8"))
        pdf_part = MIMEApplication(pdf_attachment, _subtype="pdf")
        pdf_part.add_header(
            "Content-Disposition", "attachment", filename="report.pdf"
        )
        msg.attach(pdf_part)
    else:
        msg = MIMEMultipart("alternative")
        msg.attach(MIMEText(html_body, "html", "utf-8"))

    # report_to_email may be comma-separated; build explicit recipient list.
    recipients = [a.strip() for a in (settings.report_to_email or "").split(",") if a.strip()]

    msg["Subject"] = subject
    msg["From"] = settings.smtp_from_email
    msg["To"] = ", ".join(recipients)

    # Port 465 = implicit TLS (connection starts encrypted).
    # Port 587 (or other) = STARTTLS (plain → upgrade) when TLS is enabled.
    use_implicit_tls = settings.smtp_use_tls and settings.smtp_port == 465
    use_starttls = settings.smtp_use_tls and not use_implicit_tls

    await aiosmtplib.send(
        msg,
        hostname=settings.smtp_host,
        port=settings.smtp_port,
        username=settings.smtp_username or None,
        password=smtp_password,
        recipients=recipients,
        use_tls=use_implicit_tls,
        start_tls=use_starttls,
    )


async def test_smtp_connection(settings: AppSettings, master_key: bytes) -> None:
    """
    Verify SMTP connectivity by connecting and authenticating.
    Does not send any email. Does not require email_enabled.

    Raises:
        RuntimeError: If SMTP host/port/from/to are not configured.
        aiosmtplib.SMTPException: On connection or authentication failure.
    """
    _check_smtp_config(settings)

    smtp_password: str | None = None
    if settings.smtp_password_enc:
        smtp_password = decrypt(settings.smtp_password_enc, master_key)

    await test_smtp_connection_from_params(
        smtp_host=settings.smtp_host,
        smtp_port=settings.smtp_port,
        smtp_username=settings.smtp_username,
        smtp_password=smtp_password,
        smtp_use_tls=settings.smtp_use_tls,
    )


async def test_smtp_connection_from_params(
    *,
    smtp_host: str | None,
    smtp_port: int | None,
    smtp_username: str | None,
    smtp_password: str | None,
    smtp_use_tls: bool | None,
) -> None:
    """
    Verify SMTP connectivity using raw parameters (for testing before save).

    Raises:
        RuntimeError: If smtp_host is missing.
        aiosmtplib.SMTPException: On connection or authentication failure.
    """
    if not smtp_host:
        raise RuntimeError("SMTP host is required.")

    port = smtp_port or 587
    use_tls = smtp_use_tls if smtp_use_tls is not None else True

    # Port 465 = implicit TLS; port 587 (or other) = STARTTLS when TLS enabled.
    use_implicit_tls = use_tls and port == 465

    smtp = aiosmtplib.SMTP(
        hostname=smtp_host,
        port=port,
        use_tls=use_implicit_tls,
    )
    await smtp.connect()
    try:
        if use_tls and not use_implicit_tls:
            await smtp.starttls()
        if smtp_username:
            await smtp.login(smtp_username, smtp_password or "")
    finally:
        await smtp.quit()


async def test_smtp_send_from_params(
    *,
    smtp_host: str | None,
    smtp_port: int | None,
    smtp_username: str | None,
    smtp_password: str | None,
    smtp_use_tls: bool | None,
    smtp_from_email: str | None,
    report_to_email: str | None,
) -> list[str]:
    """
    Send a test email using raw SMTP parameters (for testing before save).

    Returns the list of recipient addresses the message was sent to.

    Raises:
        RuntimeError: If required fields are missing.
        aiosmtplib.SMTPException: On SMTP connection or delivery failure.
    """
    missing: list[str] = []
    if not smtp_host:
        missing.append("SMTP host")
    if not smtp_from_email:
        missing.append("From address")
    if not report_to_email:
        missing.append("Send reports to")
    if missing:
        raise RuntimeError(f"Configure these fields first: {', '.join(missing)}.")

    port = smtp_port or 587
    use_tls = smtp_use_tls if smtp_use_tls is not None else True

    msg = MIMEText(
        "This is a test email from YNAB Financial Report.\n\n"
        "If you received this, your SMTP settings are configured correctly.",
        "plain",
        "utf-8",
    )
    recipients = [a.strip() for a in (report_to_email or "").split(",") if a.strip()]

    msg["Subject"] = "YNAB Financial Report \u2014 SMTP test"
    msg["From"] = smtp_from_email or ""
    msg["To"] = ", ".join(recipients)

    use_implicit_tls = use_tls and port == 465

    smtp = aiosmtplib.SMTP(
        hostname=smtp_host,
        port=port,
        use_tls=use_implicit_tls,
    )
    await smtp.connect()
    try:
        if use_tls and not use_implicit_tls:
            await smtp.starttls()
        if smtp_username:
            await smtp.login(smtp_username, smtp_password or "")
        await smtp.send_message(msg, recipients=recipients)
    finally:
        await smtp.quit()

    return recipients
